### PR TITLE
add gl-draw v0.12.0

### PR DESCRIPTION
**Pull request by ghoshkaj**
Add gl-draw v0.12.0

### CODE REVIEW

**Comment by ghoshkaj** [comment]
@mollymerp I'm attempting to add the latest draw version here. @mcwhittemore and I were wondering how to test that this PR works. Would you let us know please? Thanks!

**Comment by mollymerp** [comment]
Great question... I don't think there's a legit way to test. You just run `npm run deploy` and then check the link to make sure its hosted properly ☁️ 

Note that once you deploy this, you should make a companion PR that updates the version [here](https://github.com/mapbox/mapbox-gl-js/blob/master/docs/_posts/plugins/0100-01-01-mapbox-gl-draw.html)

**Comment by ghoshkaj** [comment]
@mollymerp okay cool thanks. The reason we were asking was because of [this comment](https://github.com/mapbox/mapbox-gl-plugins/pull/18#issuecomment-243812240)  when you were reviewing the last version PR. Was it just regular gl-draw tests you ran then?

**Comment by mollymerp** [comment]
Oooh I just tested the files you have here locally with a gl-js file... we could make a debug page to make this easier in the future 💭

**Comment by ghoshkaj** [comment]
@mollymerp ohh aha, I see. Cool Thanks! Deploying now!

**Pull request merged**
