### PR TITLE
mapbox-gl-draw@0.11.18

### PR DESCRIPTION
**Pull request by mcwhittemore**
@mollymerp for the review.

### CODE REVIEW

**Comment by mollymerp** [comment]
@mcwhittemore i just ran a test and it looks like this version has the weird polygon control too. Last release I just pushed a hot fix with the correct encoding of the svg but I'm not sure what the root problem is.

screen shot 2016-08-31 at 10 58 18 am

**Comment by mcwhittemore** [comment]
@mollymerp by hotfix, do you mean you took the svg from the folder and encoded it into the css file?

**Comment by mollymerp** [comment]
@mcwhittemore yep, exactly!

**Comment by mcwhittemore** [comment]
I think that should fix it

**Comment by mollymerp** [comment]
LGTM 🚢 
Once you merge, you just need to `mbx auth` and then `npm run deploy` to get it up in the ☁️

**Comment by mcwhittemore** [comment]
Thanks!

**Pull request merged**
